required_devices: 8
resume: false

no_test: false
test_only: false
debug: false
seed: 0
distributed: false
test_freq: 1
num_workers: 9

benchmark:
  name: "esc50-svm-linear-8at16"

dataset:
  name: "esc50"
  fold: 1
  batch_size: 64
  clip_duration: 2.
  video_fps: 16.
  crop_size: 224
  audio_fps: 24000.
  spectrogram_fps: 100.
  n_fft: 512
  transform: "msc+color"
  min_area: 0.08
  color: [0.4, 0.4, 0.4, 0.2]
  sample_grad_cam_audio: False
  train:
    split: "trainlist{fold:02d}"
    mode: "clip"
    clips_per_video: 10
    use_augmentation: true
    use_shuffle: true
    drop_last: true
    return_index: true
  test:
    split: "testlist{fold:02d}"
    mode: "clip"
    clips_per_video: 5
    use_augmentation: false
    use_shuffle: false
    drop_last: false
    return_index: true
  test_dense:
    split: "testlist{fold:02d}"
    mode: "video"
    clips_per_video: 10
    use_augmentation: false
    use_shuffle: false
    drop_last: false
    return_index: false

optimizer:
  name: "adam"
  num_epochs: 50
  weight_decay: 0.0
  warmup_classifier: true
  lr:
    name: "multistep"
    base_lr: 0.0001
    gamma: 0.3
    milestones: [15, 30, 40]
    save_freq: 1

model:
  name: "MOSTWrapper-Audio"
  c: 0.01
  args:
    n_classes: 25
    feat_names: "conv1x"
    pooling_ops: "AdaptiveMaxPool2d((1, 24))"
    feat_dims: 1536
    use_bn: true
    ft_all: False
